version: '3'

services:
  app: &app_base
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DATABASE_URL=postgres://postgres:password@pg:5432
    volumes:
      - .:/opt/app
      - gems:/usr/local/bundle
      - node-modules:/usr/src/app/node_modules
    ports:
      - 3000:3000
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
  webpacker:
    <<: *app_base
    command: ./bin/webpack-dev-server
    ports:
      - 3035:3035
  pg:
    image: postgres:12-alpine
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  gems:
  node-modules:
  pg-data:
